### PR TITLE
HTML respec

### PR DESCRIPTION
**Pull request by bergos**
This is a 1:1 mapping of the spec into HTML/respec. It's based on the master + #113, which was already accepted on gitter. I would propose to merge it fast and use new PRs for further improvements.

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
Great! I'm visiting at MIT this summer, we've talked about this with @dmitrizagidulin and @timbl. Would be good if we could finalize things this summer.

We'll also want to have a look at the the history of the original document to see who should be authors and editors.

**Comment by bergos** [comment]
I created an issue for adding authors and editors #119

**Comment by RubenVerborgh** [comment]
Great, I'd say #119 is a dependency for this PR though. As soon as an official-looking doc comes out, people will start citing.

**Comment by dmitrizagidulin** [comment]
👍 , looks good to me. (no opinion re authors & editors being a prereq)

**Comment by bergos** [comment]
Let's make a deadline for the credits: On Thursday I will make the last commit to this PR. Also on Thursday we merge it. Other changes to the credits must be done in another PR.

**Comment by elf-pavlik** [comment]
:+1: deadline on Thursday

BTW easy link to preview it as HTML https://rawgit.com/bergos/representation-task-force/respec/interface-spec.html

**Comment by bergos** [comment]
- copied @RubenVerborgh and @bergos also to the authors
- added @elf-pavlik to the authors

@l00mi @elf-pavlik @RubenVerborgh somebody want's to merge?

**Comment by l00mi** [comment]
I go forward and merge this to have a first version of the spec published. Please open new requests for further changes.

**Pull request merged**
