### PR TITLE
added Reader and Writer interfaces

### PR DESCRIPTION
**Pull request by bergos**

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
Note sure about the necessity of writer. Instead of writing to something, that thing could just read from you.

**Comment by bergos** [comment]
That would require to have a generic stream as return value and parameter. Should we define `Stream` without specifying the data type? `QuadStream` could inherit from `Stream` with a specific data type and be used everywhere in the spec where we have written `Stream` until now.

**Comment by RubenVerborgh** [comment]
Since JavaScript is ducktyped, it doesn't really matter; how we call it is just for the documentation. Perhaps simply `Stream<Quad>` to refer to it.

**Comment by elf-pavlik** [comment]
Any updates needed on this one?

**Comment by elf-pavlik** [comment]
green-turtle uses term *Processor*, since we may want to avoid confusion with node *Transform* and as I understand implementations will use it for both parsers and serializers, *Processor* may describe this *stream translator* better than *Reader*

**Comment by elf-pavlik** [comment]
This PR seems to miss definition of a constructor/factory, #79 suggests that constructor would allow passing factory, possibly one could also pass base as in #96

**Comment by elf-pavlik** [comment]
@bergos what do you think about changing /Reader/Processor/ & /read()/process()/ ?
next PR could address options to pass `base`, `@context` for JSON-LD serializer etc.

### Processor

A Processor is an object that translates one stream to another stream.
The input and output stream may emit quads or custom formats.
The Processor interface can be used for parsers and serializer, but also for quad or custom format transformations.
Implementations may support addition data types like String or Buffer as input

`Stream .process(Stream input)`
Creates a `Stream` which emits data based on the `input` stream.

**Comment by timbl** [comment]
If, when parsing a turtle document, or within an N3 document, you are parsing a sub graph bewteen { braves } you create a stream of triples  then do you also create a stream of nodes when you are a parsing a Collection/List/Array between ( parentheses) ?

**Comment by RubenVerborgh** [comment]
@timbl I'd say that everything is a stream of triples (for consistency). So
parsing a list leads to a stream of rdf:first/rdf:rest. That's how current
streaming parsers in JavaScript work. Would this be problematic for N3,
which gives lists a first-class status? In any case, switching types
mid-stream seems difficult.

(Different but perhaps related: I recently was in touch with @josd
regarding the equal treatment of lists In EYE from N3/Turtle/N-Triples
input, so no special treatment seems necessary.)

**Comment by elf-pavlik** [comment]
> @timbl: If, when parsing a turtle document, or within an N3 document, you are parsing a sub graph bewteen { braves } you create a stream of triples

> @RubenVerborgh: I'd say that everything is a stream of triples (for consistency).

Parser should return stream of Quads, (where we have Triple as alias of quad with .graph always set to DefaultGraph). AFAIK @blake-regalia trig/n-quads parser in graphy.js streams quads as well as @RubenVerborgh's trig/n3/n-quads parser in N3.js

I must admit not having much familiarity with N3, I don't know how 'sub graph' in N3 differs from 'named graph' in Trig/N-Quads. I also remember @RubenVerborgh [asking very specific question about N3 lists in a chatroom](https://gitter.im/rdfjs/Representation-Task-Force?at=580e21ac9aea834129e9fbc2) which possibly @timbl never answered there. If N3 has some additional requirements besides requirements of all the [official RDF1.1 serializations](https://www.w3.org/TR/rdf11-new/#section-serializations) maybe it would make sense to start documenting them in dedicated .md file or on wiki page? This would also help everyone to better understand N3 :smile:

**Comment by bergos** [comment]
After playing a little bit with the interfaces, I don't think we need to distinguish between reader, writer or processor. We have already the `.import` method of the `Sink` interface. With [that PR](https://github.com/rdfjs/representation-task-force/pull/110) it will return an EventEmitter. I think it's required to track the status of the import. That PR has already some +1s.

`EventEmitter .import(Stream stream)` should cover everything we need. `EventEmitter` can be also a `Stream`. `Stream` is not exclusive for `Quad`, but can be also used for byte and object streams. Here is list of use cases and subtypes, which are all covered by the method:

**Parser**
`Stream<Quad>|Source .import(Stream stream)`

**Serializer**
`Stream .import(Stream<Quad>|Source stream)`

**Transformation**
`Stream<Quad>|Source .import(Stream<Quad>|Source stream)`

**Store**
`EventEmitter .import(`EventEmitter .import(Stream stream)` stream)`

Instead of adding more interfaces, I would propose to change the description of the method. Optional we can even mention the subtypes explicitly.

If we should close this PR and create a new one with the extended description, please +1 on this comment.

**Comment by elf-pavlik** [comment]
https://github.com/rdfjs/representation-task-force/blob/master/interface-spec.md#sink
> A Sink is an object that consumes quads. It can store the quads or do some further processing. For example serializers and transformations which consume quads can implement the Sink interface.
>*  undefined .import(Stream stream) Writes all quads from the stream to the sink.

So `.import` would accept any Stream, and for Store we should clarify that in only accepts `Stream<Quad>` (just like serializer and transformation)

**Comment by elf-pavlik** [comment]
Noticing #79 and how rdf-ext implements it https://github.com/rdf-ext/rdf-ext/blob/develop/lib/parsers.js#L33

It seems that `import()` should also accept `options` parameter, which also has long discussion in #44

**Pull request closed without merging**
