### PR TITLE
added optional label parameter for .blankNode()

### PR DESCRIPTION
**Pull request by bergos**

### CODE REVIEW

**Comment by dmitrizagidulin** [comment]
👍

**Comment by dmitrizagidulin** [comment]
👍

**Comment by bergos** [comment]
Should solve [this issue](https://github.com/rdfjs/representation-task-force/issues/30).

**Comment by dmitrizagidulin** [comment]
👍

**Comment by elf-pavlik** [comment]
RDF specs call it an *identifier* not a label
https://www.w3.org/TR/rdf11-concepts/#dfn-blank-node-identifier

**Comment by elf-pavlik** [comment]
cherry-picked in https://github.com/rdfjs/representation-task-force/commit/213a79e9d545bdbb57f41cdf49934496d738d9bc

**Pull request closed without merging**
