### PR TITLE
Add UML diagram

### PR DESCRIPTION
**Pull request by pieroit**
Can't include the .svg in the document, so I also prepared a .png version.

### CODE REVIEW

**Comment by bergos** [comment]
Looks nice :-)

But we should wait till other issues are closed. These could/will have an impact: [#10](https://github.com/rdfjs/representation-task-force/pull/10) [#12](https://github.com/rdfjs/representation-task-force/pull/12) [#23](https://github.com/rdfjs/representation-task-force/pull/23)

**Comment by pieroit** [comment]
Great, I'll update once those are resolved

**Comment by l00mi** [comment]
@pieroit We merged the pull requests. Looking forward to the new version. Thanks!

**Comment by pieroit** [comment]
@l00mi done :)

**Comment by l00mi** [comment]
Looks good! Thanks @pieroit.

@bergos The DefaultGraph in the UML should not be in paragraphs because it is not a string. Right?

**Comment by bergos** [comment]
@l00mi Yes, the default graph in the triple is an instance of DefaultGraph.
@pieroit Everything else looks good :+1:

**Comment by pieroit** [comment]
@l00mi @bergos I'll fix it today ;)

**Pull request merged**
