### PR TITLE
update UML

### PR DESCRIPTION
**Pull request by pieroit**
Please leave PR open as many details are still to be defined. See #68.

### CODE REVIEW

**Comment by elf-pavlik** [comment]
@pieroit we've merged pending pull requests, could you update the diagram so we can merge this one?

**Comment by pieroit** [comment]
@elf-pavlik yes I will update asap

**Comment by pieroit** [comment]
@elf-pavlik 
- data UML updated
- stream UML added

**Comment by elf-pavlik** [comment]
awesome! thanks @pieroit

**Pull request merged**
